#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-RAI-TrackBack
version:      0.1
version_from: lib/XML/RAI/TrackBack.pm
installdirs:  site
requires:
    XML::RAI:                      1.3
    File::Spec:                    0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
